### ISSUE TITLE
Cannot read properties of null (reading 'setupContext')

### ISSUE THREAD

**Issue by Maxchii** [HC200ok/vue3-easy-data-table#185]
useSlots() seems to be causing a `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setupContext')` error when installing V1.5.22 using Yarn. Code fails at `return i.setupContext || (i.setupContext = createSetupContext(i));` because `const i = getCurrentInstance();` is null. 

Could vue3-easy-data-table support non-global injection? I'd like to import the component only where I need it.

Stack trace:

``` Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setupContext')
    at getContext (runtime-core.esm-bundler.js:7574:14)
    at useSlots (runtime-core.esm-bundler.js:7564:12)
    at setup (vue3-easy-data-table.es.js:1290:19)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7188:29)
    at setupComponent (runtime-core.esm-bundler.js:7143:11)
    at mountComponent (runtime-core.esm-bundler.js:5495:13)
    at processComponent (runtime-core.esm-bundler.js:5470:17)
    at patch (runtime-core.esm-bundler.js:5060:21)
    at mountChildren (runtime-core.esm-bundler.js:5256:13)

**Comment by Maxchii** [comment]
Seems to be related to #163, as updating vue fixes the issue. vue `3.2.45` should probably be stated as minimum requirement.

**Comment by HOPELESSNESSLYR** [comment]
How to solve this problem?"Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setupContext')"

**Comment by seyfer** [comment]
@Maxchii this is indeed a piece of important information. Updating Vue 3 to latest solved it for me.
