### ISSUE TITLE
Problem in vue3-easy-data-table

### ISSUE THREAD

**Issue by LAILA289** [HC200ok/vue3-easy-data-table#240]
Hello i have problem i installed vue3-easy-data-table
and i used this code but i get error can i found someone ti fix me this 
code:
<template>
 
    <EasyDataTable :headers="headers" :items="items" />

</template>
<script>

export default {
  data(){
    return {
      
      headers: [
  { text: "PLAYER", value: "player" },
  { text: "TEAM", value: "team"},
  { text: "NUMBER", value: "number"},
  { text: "POSITION", value: "position"},
  { text: "HEIGHT", value: "indicator.height"},
  { text: "WEIGHT (lbs)", value: "indicator.weight", sortable: true},
  { text: "LAST ATTENDED", value: "lastAttended", width: 200},
  { text: "COUNTRY", value: "country"},
],
    items:[
  { player: "Stephen Curry", team: "GSW", number: 30, position: 'G', indicator: {"height": '6-2', "weight": 185}, lastAttended: "Davidson", country: "USA"},
  { player: "Lebron James", team: "LAL", number: 6, position: 'F', indicator: {"height": '6-9', "weight": 250}, lastAttended: "St. Vincent-St. Mary HS (OH)", country: "USA"},
  { player: "Kevin Durant", team: "BKN", number: 7, position: 'F', indicator: {"height": '6-10', "weight": 240}, lastAttended: "Texas-Austin", country: "USA"},
  { player: "Giannis Antetokounmpo", team: "MIL", number: 34, position: 'F', indicator: {"height": '6-11', "weight": 242}, lastAttended: "Filathlitikos", country: "Greece"},
],
    };
  },
 
};
</script>
<style></style>
issue:
 
       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setupContext')
    at getContext (runtime-core.esm-bundler.js?20a8:7609:1)
    at useSlots (runtime-core.esm-bundler.js?20a8:7599:1)
    at setup (vue3-easy-data-table.es.js?ed00:1305:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?d2dd:157:1)
    at setupStatefulComponent (runtime-core.esm-bundler.js?d2dd:7246:1)
    at setupComponent (runtime-core.esm-bundler.js?d2dd:7200:1)
    at mountComponent (runtime-core.esm-bundler.js?d2dd:5524:1)
    at processComponent (runtime-core.esm-bundler.js?d2dd:5499:1)
    at patch (runtime-core.esm-bundler.js?d2dd:5101:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js?d2dd:5638:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js?89dc:187:1)
    at instance.update (runtime-core.esm-bundler.js?d2dd:5745:1)
    at setupRenderEffect (runtime-core.esm-bundler.js?d2dd:5759:1)
    at mountComponent (runtime-core.esm-bundler.js?d2dd:5541:1)
    at processComponent (runtime-core.esm-bundler.js?d2dd:5499:1)
    at patch (runtime-core.esm-bundler.js?d2dd:5101:1)
getContext @ runtime-core.esm-bundler.js?20a8:7609
useSlots @ runtime-core.esm-bundler.js?20a8:7599
setup @ vue3-easy-data-table.es.js?ed00:1305
callWithErrorHandling @ runtime-core.esm-bundler.js?d2dd:157
setupStatefulComponent @ runtime-core.esm-bundler.js?d2dd:7246
setupComponent @ runtime-core.esm-bundler.js?d2dd:7200
mountComponent @ runtime-core.esm-bundler.js?d2dd:5524
processComponent @ runtime-core.esm-bundler.js?d2dd:5499
patch @ runtime-core.esm-bundler.js?d2dd:5101
componentUpdateFn @ runtime-core.esm-bundler.js?d2dd:5638
run @ reactivity.esm-bundler.js?89dc:187
instance.update @ runtime-core.esm-bundler.js?d2dd:5745
setupRenderEffect @ runtime-core.esm-bundler.js?d2dd:5759
mountComponent @ runtime-core.esm-bundler.js?d2dd:5541
processComponent @ runtime-core.esm-bundler.js?d2dd:5499
patch @ runtime-core.esm-bundler.js?d2dd:5101
componentUpdateFn @ runtime-core.esm-bundler.js?d2dd:5711
run @ reactivity.esm-bundler.js?89dc:187
instance.update @ runtime-core.esm-bundler.js?d2dd:5745
callWithErrorHandling @ runtime-core.esm-bundler.js?d2dd:157
flushJobs @ runtime-core.esm-bundler.js?d2dd:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js?d2dd:282
queuePostFlushCb @ runtime-core.esm-bundler.js?d2dd:304
queueEffectWithSuspense @ runtime-core.esm-bundler.js?d2dd:1585
scheduler @ runtime-core.esm-bundler.js?d2dd:1820
triggerEffect @ reactivity.esm-bundler.js?89dc:397
triggerEffects @ reactivity.esm-bundler.js?89dc:387
triggerRefValue @ reactivity.esm-bundler.js?89dc:1003
eval @ reactivity.esm-bundler.js?89dc:1137
triggerEffect @ reactivity.esm-bundler.js?89dc:397
triggerEffects @ reactivity.esm-bundler.js?89dc:382
triggerRefValue @ reactivity.esm-bundler.js?89dc:1003
eval @ reactivity.esm-bundler.js?89dc:1137
triggerEffect @ reactivity.esm-bundler.js?89dc:397
triggerEffects @ reactivity.esm-bundler.js?89dc:382
triggerRefValue @ reactivity.esm-bundler.js?89dc:1003
set value @ reactivity.esm-bundler.js?89dc:1048
finalizeNavigation @ vue-router.mjs?f169:3334
eval @ vue-router.mjs?f169:3207
Promise.then (async)
pushWithRedirect @ vue-router.mjs?f169:3173
push @ vue-router.mjs?f169:3099
install @ vue-router.mjs?f169:3530
use @ runtime-core.esm-bundler.js?d2dd:4381
eval @ main.js?fbea:28
./src/main.js @ app.js:542
__webpack_require__ @ app.js:2323
(anonymous) @ app.js:3444
__webpack_require__.O @ app.js:2369
(anonymous) @ app.js:3445
(anonymous) @ app.js:3447

**Comment by sunil-dzango** [comment]
I am getting pretty much the same issue. Tried with both Option and Composition API, and also tried downgrading the versions. But I am still getting these errors.

```[Vue warn]: useCssVars is called without current active component instance.
warn2 @ runtime-core.esm-bundler.js:40`
[Vue warn]: provide() can only be used inside setup().
warn2 @ runtime-core.esm-bundler.js:40`
[Vue warn]: useContext() called without active instance.
warn2 @ runtime-core.esm-bundler.js:40`
[Vue warn]: Unhandled error during execution of setup function
  ```

```
vue-router.esm-bundler.js:3302 TypeError: Cannot read properties of null (reading 'setupContext')
    at getContext (runtime-core.esm-bundler.js:7609:14)
    at useSlots (runtime-core.esm-bundler.js:7599:12)
    at setup (vue3-easy-data-table.es.js:1305:19)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7056:29)
    at setupComponent (runtime-core.esm-bundler.js:7012:11)
    at mountComponent (runtime-core.esm-bundler.js:4922:13)
    at processComponent (runtime-core.esm-bundler.js:4897:17)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at mountChildren (runtime-core.esm-bundler.js:4685:13)
triggerError @ vue-router.esm-bundler.js:3302
```

**Comment by dieguezz** [comment]
This is not a problem with the library. I made a reproduction for you [here](https://codesandbox.io/s/elated-stitch-w9k34b?file=/src/components/HelloWorld.vue)

**Comment by sunil-dzango** [comment]
I downloaded your sandox and ran on my PC, and I am still getting the same error. May I ask which node versions are you using?

**Comment by dieguezz** [comment]
@sunil-dzango you can check it in package.json [here](https://codesandbox.io/s/elated-stitch-w9k34b?file=/package.json)

**Comment by thekarinka** [comment]
Seems to be related to https://github.com/HC200ok/vue3-easy-data-table/issues/163, as updating vue to version 3.2.45 fixes the issue.

**Comment by ricardobuquet** [comment]
Same issue here, tried upgrading the library and vue, removing my lock file, my modules and nothing

**Comment by kezek** [comment]
Having the same issue since I've upgraded to Vue 3.3.x. Used to work fine with Vue 3.2.x
