### ISSUE TITLE
Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by Tchoupinax** [HC200ok/vue3-easy-data-table#93]
Hello,

I just tried to install your package and I met this issue.

```
vue3-easy-data-table.es.js:772 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at getItemValue (vue3-easy-data-table.es.js:772:14)
    at generateColumnContent (vue3-easy-data-table.es.js:783:19)
    at vue3-easy-data-table.es.js:1314:86
    at renderList (runtime-core.esm-bundler.js:2884:22)
    at vue3-easy-data-table.es.js:1296:74
    at renderList (runtime-core.esm-bundler.js:2884:22)
```

<img width="947" alt="image" src="https://user-images.githubusercontent.com/9136206/183125590-e06d09da-12b4-46aa-a8ba-a05ea234769f.png">

The exemple code

```
<template>
  <Vue3EasyDataTable
    :headers="headers"
    :items="items"
  />
</template>

<script lang="ts">
import type { Header, Item } from "vue3-easy-data-table";
import Vue3EasyDataTable from 'vue3-easy-data-table';
import 'vue3-easy-data-table/dist/style.css';


export default {
    components: {
      Vue3EasyDataTable,
    },
    data () {
      return {
        headers: [
          { text: "PLAYER", value: "player" },
          { text: "TEAM", value: "team"},
          { text: "NUMBER", value: "number"},
          { text: "POSITION", value: "position"},
          { text: "HEIGHT", value: "indicator.height"},
          { text: "WEIGHT (lbs)", value: "indicator.weight", sortable: true},
          { text: "LAST ATTENDED", value: "lastAttended", width: 200},
          { text: "COUNTRY", value: "country"},
        ],
        items: [
          { player: "Stephen Curry", team: "GSW", number: 30, position: 'G', indicator: {"height": '6-2', "weight": 185}, lastAttended: "Davidson", country: "USA"},
          { player: "Lebron James", team: "LAL", number: 6, position: 'F', indicator: {"height": '6-9', "weight": 250}, lastAttended: "St. Vincent-St. Mary HS (OH)", country: "USA"},
          { player: "Kevin Durant", team: "BKN", number: 7, position: 'F', indicator: {"height": '6-10', "weight": 240}, lastAttended: "Texas-Austin", country: "USA"},
          { player: "Giannis Antetokounmpo", team: "MIL", number: 34, position: 'F', indicator: {"height": '6-11', "weight": 242}, lastAttended: "Filathlitikos", country: "Greece"},
        ],
      }
    },
  }
</script>
```

Have a nice day!

**Comment by HC200ok** [comment]
@Tchoupinax Could you provide more details such as the version, It seems no problem with the newest version
 https://codesandbox.io/s/via-cdn-forked-k4nlll?file=/index.html
